os:
  - linux
  - osx

language: c++
python:
  - '2.7'
addons:
  apt:
    packages:
      - python-pip
sudo: false

branches:
  only:
    - master

-notifications:   
   slack: 
     rooms:
       - faederlab:l0waIGp58v8ZV74N7QmXGoWs      
     template:
       - "BioNetGen build: %{result} in %{duration}"
       - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)    Author: %{author}"
       - "Build details:  %{build_url} "

script:
  - cd ./bng2
  # build atomizer (a little less easy...)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y python3-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y python3.4-venv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  # build sbmltranslator, nfsim, distribution and validate
  - make dist
  - "mv ./BioNetGen-2.3.2.tgz ./BioNetGen-2.3.2-${TRAVIS_OS_NAME}.tgz"
  - make test
  - cd ..

deploy:
  provider: bintray
  file: "./bintray.json"
  user: jczech
  key:
    # If you need to regenrate this for some reason, here's what you do:
    # travis encrypt <YOUR BINTRAY API KEY> --add deploy.key
    # Get BINTRAY API KEY from https://bintray.com/profile/edit under "API Key" section
    secure: Fy2jOUE+HwCMo219mmdu9p0l/+p28DQ0VQORhER6xan59U4pMYYWeNZ1g1YXFsDulEcedMNqbcI2Voeh5U8m9evsIanKp7/181TZ6ZX0K1kdpPuUmtuAPTRMVz7u1cYVgk2nzsBGI1OAj/guUThfCQBUumrJp52zB28dnlBiAwFPf1neO8M9khqRjzx98KCj2p4lMTj9z7KLSehtqNpMRU5bo+HaWca5XyKHcetRL0qpwRVhb0TcrL9z9ryCD4aXeRx3A3f2KQBQjV67F2xXbHLvljUdKW20nLQPwtFrRHn2HCEkYVZHq5zqsPlc1iDV6irDNbno+XHRpigriAoixx2C5Xb5Ah5+qD61eG719OXab5eYG/dye9mqjvPojwHN5Gd53sRbI707w3rT1YbqeN7wnEYHK7lgkyCx1D9vInp0THrLxyC/rJ0R+xneK7odHrWhLNtQWE3ZV9adDFrZuNVn3X28iJDWyfxNDgEoffZ9QSuinWlv/ITK+kYYYkQT73gH0QEtQC5Yzby73w1lK/SRbJeyBUYvR1xXKev8ToSD84VL3yMOz4Mi2ouRmJYmIlJiuv+q5ibNduD9CCi1t0arsPG15PTEaKAgQ8BELDO3V5HQkjM//4ftrchNW3WmiPwNwMisP8UDi63kS3BGr1v4QWYXmxCJu0WyF9pH+2c=
  skip_cleanup: true
  on:
    all_branches: true
